title: CoffeeBreakCyber
author: Das-12
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
